services:
  web:
    build: .
    ports:
      - "5051:5000"
    env_file:
      - .env
    environment:
      TZ: America/Toronto
    volumes:
      - reservation_data:/data

volumes:
  reservation_data:
